// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package blocklist

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson2d7d9c89DecodeEthMappingContractContractBlocklist(in *jlexer.Lexer, out *SeedBlocksParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_header":
			out.BlockHeader = string(in.String())
		case "block_height":
			out.BlockHeight = uint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2d7d9c89EncodeEthMappingContractContractBlocklist(out *jwriter.Writer, in SeedBlocksParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_header\":"
		out.RawString(prefix[1:])
		out.String(string(in.BlockHeader))
	}
	{
		const prefix string = ",\"block_height\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.BlockHeight))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SeedBlocksParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2d7d9c89EncodeEthMappingContractContractBlocklist(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SeedBlocksParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2d7d9c89DecodeEthMappingContractContractBlocklist(l, v)
}
func tinyjson2d7d9c89DecodeEthMappingContractContractBlocklist1(in *jlexer.Lexer, out *AddBlocksParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]string, 0, 4)
					} else {
						out.Blocks = []string{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Blocks = append(out.Blocks, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson2d7d9c89EncodeEthMappingContractContractBlocklist1(out *jwriter.Writer, in AddBlocksParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix[1:])
		if in.Blocks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Blocks {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AddBlocksParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson2d7d9c89EncodeEthMappingContractContractBlocklist1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AddBlocksParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson2d7d9c89DecodeEthMappingContractContractBlocklist1(l, v)
}
