// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package mapping

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjsonA17a9c65DecodeEthMappingContractContractMapping(in *jlexer.Lexer, out *TransferParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "to":
			out.To = string(in.String())
		case "amount":
			out.Amount = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping(out *jwriter.Writer, in TransferParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix[1:])
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v TransferParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *TransferParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping1(in *jlexer.Lexer, out *SystemSupply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "active_supply":
			out.ActiveSupply = uint64(in.Uint64())
		case "user_supply":
			out.UserSupply = uint64(in.Uint64())
		case "fee_supply":
			out.FeeSupply = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping1(out *jwriter.Writer, in SystemSupply) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"active_supply\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.ActiveSupply))
	}
	{
		const prefix string = ",\"user_supply\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.UserSupply))
	}
	{
		const prefix string = ",\"fee_supply\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeSupply))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v SystemSupply) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping1(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *SystemSupply) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping1(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping2(in *jlexer.Lexer, out *RouterContract) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "contract_id":
			out.ContractId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping2(out *jwriter.Writer, in RouterContract) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractId))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v RouterContract) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping2(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *RouterContract) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping2(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping3(in *jlexer.Lexer, out *PublicKeys) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "primary_pub_key":
			out.PrimaryPubKey = string(in.String())
		case "backup_pub_key":
			out.BackupPubKey = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping3(out *jwriter.Writer, in PublicKeys) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"primary_pub_key\":"
		out.RawString(prefix[1:])
		out.String(string(in.PrimaryPubKey))
	}
	{
		const prefix string = ",\"backup_pub_key\":"
		out.RawString(prefix)
		out.String(string(in.BackupPubKey))
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v PublicKeys) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping3(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *PublicKeys) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping3(l, v)
}
func tinyjsonA17a9c65DecodeEthMappingContractContractMapping4(in *jlexer.Lexer, out *MapParams) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "tx_data":
			out.TxData = string(in.String())
		case "instructions":
			if in.IsNull() {
				in.Skip()
				out.Instructions = nil
			} else {
				in.Delim('[')
				if out.Instructions == nil {
					if !in.IsDelim(']') {
						out.Instructions = make([]string, 0, 4)
					} else {
						out.Instructions = []string{}
					}
				} else {
					out.Instructions = (out.Instructions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Instructions = append(out.Instructions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjsonA17a9c65EncodeEthMappingContractContractMapping4(out *jwriter.Writer, in MapParams) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"tx_data\":"
		out.RawString(prefix[1:])
		out.String(string(in.TxData))
	}
	{
		const prefix string = ",\"instructions\":"
		out.RawString(prefix)
		if in.Instructions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Instructions {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v MapParams) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjsonA17a9c65EncodeEthMappingContractContractMapping4(w, v)
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *MapParams) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjsonA17a9c65DecodeEthMappingContractContractMapping4(l, v)
}
